name: Build and Upload Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone Clang Prebuilt Toolchain
        run: |
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r487747c.git
          cd android_prebuilts_clang_host_linux-x86_clang-r487747c
          git checkout 14.0

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev git

      - name: Build Kernel
        run: |
          cd path/to/your/kernel/source
          export PATH=$PATH:$(pwd)/path/to/android_prebuilts_clang_host_linux-x86_clang-r487747c/clang/bin
          make clean && make

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: kernel-binaries
          path: |
            path/to/your/kernel/binaries/*
