name: Clone GitLab Repo

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Clone GitLab repository
        run: |
          git clone --branch 14.0 https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r487747c.git
          
